version: '3.9'
services:
  postgres:
    container_name: db
    network_mode: my-network
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - POSTGRES_DB=blogx_db
    volumes:
      - 'pg_data_blogx:/var/lib/postgresql/data'
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5432:5432'
    restart: always
    image: 'postgres:15.1-alpine'
  redis:
    container_name: redis
    network_mode: my-network
    ports:
      - '6379:6379'
    restart: always
    image: 'redis:7-alpine'
  haproxy:
    container_name: haproxy
    network_mode: my-network
    ports:
      - '8000:80'
    restart: always
    image: sohamkr/blogx_haproxy:0.0
    # build:
    #   context: ./haproxy/
    #   dockerfile: Dockerfile
  api_auth:
    container_name: auth
    network_mode: my-network
    environment:
      - POSTGRES_DB=blogx_db
      - POSTGRES_PASSWORD=foobarbaz
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=foobarbaz
      - DB_NAME=blogx_db
      - PORT=8080
      - JWT_SECRET_KEY=blogx_secret_key
      - BCRYPT_SALT_VALUE=12
      - 'DB_URL=postgres://postgres:foobarbaz@db:5432/blogx_db?sslmode=disable'
    ports:
      - '8080:8080'
    restart: always
    links:
      - postgres
    image: 'sohamkr/blogx_auth:0.0'
    # build:
    #   context: ./authentication/
    #   dockerfile: Dockerfile
  api_blog:
    container_name: blog
    network_mode: my-network
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=foobarbaz
      - DB_NAME=blogx_db
      - PORT=8081
      - JWT_SECRET_KEY=blogx_secret_key
      - BCRYPT_SALT_VALUE=12
      - 'DB_URL=postgres://postgres:foobarbaz@db:5432/blogx_db?sslmode=disable'
    ports:
      - '8081:8081'
    restart: always
    links:
      - postgres
    image: 'sohamkr/blogx_blog:0.0'
    # build:
      # context: ./blog/
      # dockerfile: Dockerfile
  api_feed:
    container_name: feed
    network_mode: my-network
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=foobarbaz
      - DB_NAME=blogx_db
      - PORT=8082
      - JWT_SECRET_KEY=blogx_secret_key
      - BCRYPT_SALT_VALUE=12
      - 'DB_URL=postgres://postgres:foobarbaz@db:5432/blogx_db?sslmode=disable'
    ports:
      - '8082:8082'
    restart: always
    links:
      - postgres
    image: 'sohamkr/blogx_feed:0.0'
    # build:
      # context: ./feed/
      # dockerfile: Dockerfile
  api_user:
    container_name: user
    network_mode: my-network
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=foobarbaz
      - DB_NAME=blogx_db
      - PORT=8083
      - JWT_SECRET_KEY=blogx_secret_key
      - BCRYPT_SALT_VALUE=12
      - 'DB_URL=postgres://postgres:foobarbaz@db:5432/blogx_db?sslmode=disable'
    ports:
      - '8083:8083'
    restart: always
    links:
      - postgres
    image: 'sohamkr/blogx_user:0.1'
    # build:
      # context: ./user/
      # dockerfile: Dockerfile
  swagger_ui:
    container_name: swagger
    network_mode: my-network
    ports:
      - '8084:8084'
    restart: always
    image: 'sohamkr/blogx_swagger:0.0'
    # build:
      # context: ./swagger/
      # dockerfile: Dockerfile
volumes:
  pg_data_blogx:
networks:
  my-network:
    driver: bridge
