apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: swagger-ui
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/blogx-backend-go-default: "true"
        io.kompose.service: swagger-ui
    spec:
      containers:
        - image: sohamkr/blogx_swagger:0.0
          name: swagger
          ports:
            - containerPort: 8084
          resources: {}
      restartPolicy: Always
status: {}
